name: Close PR
on: pull_request
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
    - uses: dessant/repo-lockdown@v2
      with:
        github-token: ${{ github.token }}
        pr-comment: "@${pull_request.user.login}, pull requests are not used in this repository. See the [Contributing.md](https://github.com/wrye-bash/wrye-bash/blob/dev/Contributing.md#contributing-code) document on how to contribute code."
        lock-pr: false
        process-only: prs
